#! /bin/bash
#
# Test expiration for tcp_probe_wait
#

topdir=$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd -P)

# ipref3 --length 8k --bitrate 1280k --pacing-timer 200000
# This should send 32k bursts every 200ms, not enough for a probe to ever accumulate
export IPERF_V3=1
export IPERF_CLIENT_EXTRA_ARGS="--length 8k --bitrate 1280k --pacing-timer 200000"
if [[ -f /proc/sys/net/ipv4/tcp_probe_wait ]]; then
    export EXTRA_CLIENT_CMD="sysctl -w net.ipv4.tcp_probe_wait=100;$EXTRA_CLIENT_CMD"
fi
if "$topdir/test-tcp-mtu-probing" "$@"; then
    echo "not ok - should have failed"
    exit 1
else
    echo "ok - failed as expected"
    exit 0
fi
