#! /bin/bash -e

clean_netns()
{
    if ip netns list | grep -q "$1"; then
        ip netns del "$1"
    fi
}

# If $pid is set then kill wait unset
clean_bgpid()
{
    local pid=$1
    if [[ -n ${!pid} ]]; then
        kill -9 "${!pid}"
        wait "${!pid}" || true
        unset "$pid"
    fi
}

clean()
{
    clean_bgpid iperf_client_pid
    clean_bgpid iperf_server_pid
    clean_bgpid watch_ss_client_pid
    clean_bgpid tcpdump_client_pid
    clean_bgpid tcpdump_server_pid
    clean_netns ns_client
    clean_netns ns_middle
    clean_netns ns_server
    if [[ -n $tmpdir ]]; then
        rm -rf "$tmpdir"
        unset tmpdir
    fi
}

wait_loop()
{
    local max_iter=$TIMEOUT_SEC
    local sleep_interval=1
    local cmd=("$@")
    for ((iter = 0; iter < max_iter; ++iter)); do
        if "${cmd[@]}"; then
            return 0
        fi
        sleep "$sleep_interval"
    done
    return 2
}

read_last_ss_mss()
{
    tail -n1 "$LOG_DIR/watch_ss_client.log" | sed -ne "s/.* mss:\([0-9]\+\) .*/\1/pg"
}

check_mss_lo()
{
    local mss
    mss=$(read_last_ss_mss)
    echo "check mss $mss decreases to lo mtu $MTU_VALUE_LO"
    [[ $mss -lt $MTU_VALUE_LO ]]
}

check_mss_hi()
{
    local mss
    mss=$(read_last_ss_mss)
    echo "check mss $mss increases to hi mtu $MTU_VALUE_HI"
    [[ $mss -gt $((MTU_VALUE_HI - 100)) ]]
}

main()
{
    # Can be set externally:
    CLEAN=${CLEAN:-1}
    # Timeout in seconds
    TIMEOUT_SEC=${TIMEOUT_SEC:-30}
    # If set to 1 then run tcpdump (default 0)
    RUN_TCPDUMP=${RUN_TCPDUMP:-0}
    # If set to 1 then blackhole ICMPs
    ICMP_BLACKHOLE=${ICMP_BLACKHOLE:-0}
    # Override /proc/sys/net/ipv4/route/mtu_expires
    IPV4_MTU_EXPIRES=${IPV4_MTU_EXPIRES:-5}
    # Override sysctl net.ipv4.tcp_mtu_probing
    TCP_MTU_PROBING=${TCP_MTU_PROBING:-0}
    # Override sysctl net.ipv4.tcp_probe_interval
    TCP_PROBE_INTERVAL=${TCP_MTU_PROBE_INTERVAL:-5}
    # Low value for MTU test
    MTU_VALUE_LO=${MTU_VALUE_LO:-3000}
    # High value for MTU test
    MTU_VALUE_HI=${MTU_VALUE_HI:-9200}
    # IPERF --bandwith argument
    IPERF_BANDWIDTH=${IPERF_BANDWIDTH:-1024k}
    IPERF_SERVER_BANDWIDTH=${IPERF_SERVER_BANDWIDTH:-$IPERF_BANDWIDTH}
    IPERF_CLIENT_BANDWIDTH=${IPERF_CLIENT_BANDWIDTH:-$IPERF_BANDWIDTH}
    # IPERF --len argument
    IPERF_LEN=${IPERF_LEN:-128k}
    # IPERF --window argument (no custom default)
    IPERF_WINDOW=${IPERF_WINDOW:-}

    local IPERF_ARGS=()
    if [[ -n $IPERF_WINDOW ]]; then
        IPERF_ARGS+=(--window "$IPERF_WINDOW")
    fi

    clean
    if [[ $CLEAN == 1 ]]; then
        trap clean EXIT
    fi
    if [[ -z $LOG_DIR ]]; then
        tmpdir=$(mktemp -d -t "test-tcp-mtu-probing-XXXXX")
        LOG_DIR=$tmpdir
        echo "Use temporary LOG_DIR: $LOG_DIR" >&2
    else
        mkdir -p "$LOG_DIR"
        echo "Use provided LOG_DIR: $LOG_DIR" >&2
    fi

    ip netns add ns_client
    ip netns add ns_middle
    ip netns add ns_server

    ip netns exec ns_client ip link add veth_middle type veth peer name veth_client netns ns_middle
    ip netns exec ns_client ip addr add dev veth_middle 12.0.0.1/24
    ip netns exec ns_client ip link set veth_middle up mtu "$MTU_VALUE_HI"
    ip netns exec ns_middle ip addr add dev veth_client 12.0.0.2/24
    ip netns exec ns_middle ip link set veth_client up mtu "$MTU_VALUE_HI"

    ip netns exec ns_server ip link add veth_middle type veth peer name veth_server netns ns_middle
    ip netns exec ns_server ip addr add dev veth_middle 23.0.0.3/24
    ip netns exec ns_server ip link set veth_middle up mtu "$MTU_VALUE_HI"
    ip netns exec ns_middle ip addr add dev veth_server 23.0.0.2/24
    ip netns exec ns_middle ip link set veth_server up mtu "$MTU_VALUE_HI"

    ip netns exec ns_client ip route add 23.0.0.0/24 via 12.0.0.2
    ip netns exec ns_server ip route add 12.0.0.0/24 via 23.0.0.2
    ip netns exec ns_middle sysctl -w net.ipv4.ip_forward=1

    # Do proper skb segmentation, no optimizations
    ip netns exec ns_client ethtool -K veth_middle gso off tso off

    if [[ $ICMP_BLACKHOLE == 1 ]]; then
        ip netns exec ns_middle iptables -A INPUT -p icmp -j REJECT
        ip netns exec ns_middle iptables -A OUTPUT -p icmp -j REJECT
    fi

    if [[ $RUN_TCPDUMP == 1 ]]; then
        ip netns exec ns_client tcpdump -vvn -i veth_middle -w "$LOG_DIR/capture_client.pcap" &
        tcpdump_client_pid=$!
        ip netns exec ns_server tcpdump -vvn -i veth_middle -w "$LOG_DIR/capture_server.pcap" &
        tcpdump_server_pid=$!
    fi

    if false; then
        if ip netns exec ns_client ping -c3 23.0.0.3; then
            echo "ok - can ping from client to server"
        else
            echo "not ok - fail to ping from client to server"
        fi
    fi

    ip netns exec ns_client sysctl -w net.ipv4.tcp_mtu_probing="$TCP_MTU_PROBING"
    ip netns exec ns_client sysctl -w net.ipv4.tcp_probe_interval="$TCP_PROBE_INTERVAL"
    sh -c "echo '$IPV4_MTU_EXPIRES' > /proc/sys/net/ipv4/route/mtu_expires"
    ip netns exec ns_client sysctl \
            net.ipv4.ip_no_pmtu_disc \
            net.ipv4.tcp_mtu_probing \
            net.ipv4.tcp_probe_interval \
            net.ipv4.tcp_probe_threshold
    ip netns exec ns_client sysctl net.ipv4.tcp_mtu_probe_floor || true
    echo "/proc/sys/net/ipv4/route/mtu_expires: $(cat /proc/sys/net/ipv4/route/mtu_expires)"

    ip netns exec ns_server iperf \
            --bandwidth "$IPERF_SERVER_BANDWIDTH" \
            --len "$IPERF_LEN" \
            --server \
            --bind 23.0.0.3 \
            --interval 1 \
            "${IPERF_ARGS[@]}" \
            &> "$LOG_DIR/iperf_server.log" &
    iperf_server_pid=$!
    sleep 1
    ip netns exec ns_client iperf \
            --bandwidth "$IPERF_CLIENT_BANDWIDTH" \
            --len "$IPERF_LEN" \
            --client 23.0.0.3 \
            --interval 1 \
            --time 1000000 \
            --print_mss \
            "${IPERF_ARGS[@]}" \
            &> "$LOG_DIR/iperf_client.log" &
    iperf_client_pid=$!

    ip netns exec ns_client bash -c "while true; do ss --no-header --tcp --info | tee -a '$LOG_DIR/watch_ss_client.log'; sleep 1; done" &
    watch_ss_client_pid=$!

    if wait_loop check_mss_hi; then
        echo "ok - reached hi mss"
    else
        echo "not ok - failed to reach hi mss"
        exit 1
    fi

    echo "enter lo-mtu state"
    ip netns exec ns_middle ip link set veth_server mtu "$MTU_VALUE_LO"

    if wait_loop check_mss_lo; then
        echo "ok - reached lo mss"
    else
        echo "not ok - failed to reach lo mss"
        exit 1
    fi

    echo "restore hi-mtu state:"
    ip netns exec ns_middle ip link set veth_server mtu "$MTU_VALUE_HI"
    sleep 3

    if wait_loop check_mss_hi; then
        echo "ok - reached restored hi mss"
    else
        echo "not ok - failed to reach restored hi mss"
        exit 1
    fi
    exit 0
}

main "$@"
